### ISSUE TITLE
UnicodeDecodeError on Windows

### ISSUE THREAD

**Issue by lwhist** [numat/huber#25]
I get a UnicodeDecodeError when importing Bath from huber:

Exception has occurred: UnicodeDecodeError
'charmap' codec can't decode byte 0x9d in position 7416: character maps to <undefined>
  File "C:\Users\LarsGeirWhistTvedt\Documents\python\PRESSURO characterization setup\ResourceManager.py", line 4, in <module>
    from huber import Bath
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 7416: character maps to <undefined>

It was solved by adding `encoding="utf8"` in line 6 of util.py:
`with open(os.path.join(root, 'faults.csv'), encoding="utf8") as in_file:`

**Comment by alexrudd2** [comment]
Thanks for the report!  As far as I know you're the first person to run on Windows.

Windows [default character encoding](https://dev.to/methane/python-use-utf-8-mode-on-windows-212i) is causing this problem, but I think you've correctly identified the fix.

**Comment by alexrudd2** [comment]
See also [PEP597](https://peps.python.org/pep-0597/)

Does it work for you (without modifying the source) if you set `PYTHONUTF8=1`?

**Comment by lwhist** [comment]
Thanks for the quick feedback. I am new to python, so sorry for any stupid questions. Where do I set the `PYTHONUTF8=1`?

**Comment by alexrudd2** [comment]
> Thanks for the quick feedback. I am new to python, so sorry for any stupid questions. Where do I set the `PYTHONUTF8=1`?

Glad to help.
This is called setting an environment variable, and will be for all of Windows, not just Python.  There are lots of ways to do that; here's a pretty comprehensive [guide](https://phoenixnap.com/kb/windows-set-environment-variable#ftoc-heading-4).

**Comment by lwhist** [comment]
Yes, found it and that worked.
I am just wondering if that is a bit too advanced way of solving it? At least it needs to be described in readme, if so :)

**Comment by alexrudd2** [comment]
> Yes, found it and that worked. I am just wondering if that is a bit too advanced way of solving it? At least it needs to be described in readme, if so :)

Yes, it is.  The correct way is to fix the encoding as you originally mentioned, and release a new version.  However, that will take some time.   I wanted to see if setting the environment variable worked for you in the meantime. :)

**Comment by alexrudd2** [comment]
@lwhist are you interested in learning how to submit a "pull request" on GitHub?

If not, I will have @JavanW-W fix this one

**Comment by lwhist** [comment]
Sure. I have done it a few years ago, but my memory about how git works are full of holes.. ;)

**Comment by alexrudd2** [comment]
> Sure. I have done it a few years ago, but my memory about how git works are full of holes.. ;)

Hi @lwhist 
Are you still interested in submitting a [pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request)?

**Comment by lwhist** [comment]
@alexrudd2 sure, just give me a brief explanation on how to do it the correct way. :)

**Comment by alexrudd2** [comment]
> @alexrudd2 sure, just give me a brief explanation on how to do it the correct way. :)

@lwhist Ah sorry I did not see this edit.  You'll want to make a "fork" (your own personal copy) of this repository, then commit the change, then open a "pull request" for me to pull in the change.

GitHub makes this pretty easy.
Navigate to the [source file](https://github.com/numat/huber/blob/master/huber/util.py) you want to edit and click the pencil icon.
<img width="344" alt="Screenshot 2023-06-01 at 11 17 47 AM" src="https://github.com/numat/huber/assets/52292902/5f796115-e94c-4b36-850a-74bc9e429eb6">

This will guide you through making the fork.
<img width="641" alt="Screenshot 2023-06-01 at 11 18 36 AM" src="https://github.com/numat/huber/assets/52292902/80c64359-7c77-4f69-8012-fb54aa6c680d">

Make the edit you proposed (`with open(os.path.join(root, 'faults.csv'), encoding="utf8") as in_file:`) and then click Commit ("save").
<img width="1001" alt="Screenshot 2023-06-01 at 11 21 13 AM" src="https://github.com/numat/huber/assets/52292902/429c867a-0bd6-403c-8f35-b0a370a69394">

Describe the changes and click Propose Changes.  This will create a Pull Request, and we'll go from there.
<img width="600" alt="Screenshot 2023-06-01 at 11 22 22 AM" src="https://github.com/numat/huber/assets/52292902/b13aab76-204f-4a65-9827-11bd24023545">
